[package]
name = "tindalos"
version = "0.1.0"
authors = ["Steven Blowers <steven@shdblowers.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"]}
serde = { version = "1.0", features = ["derive"] }
dirs = "1.0.4"
toml = "0.5.3"