filename = "tasks.toml"

[[tasks]]
id = 0
description = "Add more tasks!"

[[tasks]]
id = 1
description = "hi there"

[[tasks]]
id = 1
description = "hi there"

[[tasks]]
id = 1
description = "boo boo boo"

